version: "3.8"

services:
  db: 
    image: postgres:12.2-alpine
    container_name: "db-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - pokenet
    volumes:
      - database_postgres:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: "rest-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - pokenet

volumes:
  database_postgres:

networks:
  pokenet:
    driver: bridge